(function(g){var window=this;var nAa=function(a,b,c,d){var e=b.oc();g.U(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.qd(c,d?d:"mqdefault.jpg");var k=b instanceof g.ZN?g.DV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.uQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.ZN?b.za:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Nn(c),is_live:m,is_list:l,
is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.wQ&&(c.playlist_length=b.getLength());a.update(c)},n5=function(a,b){g.YH.call(this,{G:"div",
aa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},o5=function(a){var b={G:"span",
L:"ytp-upnext-top",J:[{G:"span",L:"ytp-upnext-header",J:[g.V("YTP_PLAYLIST_UP_NEXT")]},{G:"span",L:"ytp-upnext-title",J:["{{title}}"]},{G:"span",L:"ytp-upnext-author",J:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.V("YTP_AUTOPLAY_NEXT")};b={G:"div",L:"ytp-upnext",U:{"aria-label":"{{watch}}"},J:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},b,{G:"a",L:"ytp-upnext-autoplay-icon",U:c,J:[{G:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
J:[{G:"circle",L:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",J:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
J:[g.V("YTP_AUTOPLAY_PAUSED_3")]}]}]};g.W.call(this,b);this.A=null;b=this.ua["ytp-upnext-cancel"];this.A=new g.W({G:"button",aa:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":g.V("YTP_AUTOPLAY_CANCEL")},J:[g.V("YTP_CANCEL")]});g.M(this,this.A);this.A.T("click",this.WO,this);this.A.va(b);this.l=a;this.I=this.ua["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.B=null;this.F=new g.Zt(this.bn,5E3,this);g.M(this,this.F);this.H=0;this.O(this.ua["ytp-upnext-autoplay-icon"],"click",
this.fR);this.eB();this.O(a,"autonavvisibility",this.eB);this.O(a,"mdxnowautoplaying",this.tQ);this.O(a,"mdxautoplaycanceled",this.uQ);this.O(a,"mdxautoplayupnext",this.MD);3==this.l.Va()&&(a=(a=g.QU(g.LU(this.l)))?a.jI():null)&&this.MD(a)},oAa=function(a,b){a.B=b;
nAa(a,b,g.Y(a.l),"hqdefault.jpg")},p5=function(a,b){if(!a.o){g.YF("a11y-announce",g.V("YTP_PLAYLIST_UP_NEXT")+" "+a.B.title);
a.H=g.iG();a.o=new g.Zt((0,g.z)(a.bq,a,b),25);a.bq(b);var c=b||g.Y(a.l).experiments.l("autoplay_time")||1E4;a.l.sa("onAutonavCoundownStarted",c)}g.tq(a.element,"ytp-upnext-autoplay-paused")},r5=function(a){q5(a);
a.H=g.iG();a.bq();g.S(a.element,"ytp-upnext-autoplay-paused")},q5=function(a){a.o&&(a.o.dispose(),a.o=null)},s5=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.l);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.ZU(a.l,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.oc(),a.bn(),a.C=new window.Notification(g.V("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.qd(c)}),a.D=a.O(a.C,"click",a.VQ),a.F.start())}q5(a);a.l.Rj(!1,b)},pAa=function(a){n5.call(this,a,"subscribecard-endscreen");
var b=a.ea();this.o=new g.W({G:"div",L:"ytp-subscribe-card",J:[{G:"img",L:"ytp-author-image",U:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",J:[{G:"div",L:"ytp-author-name",J:[b.author]},{G:"div",L:"html5-subscribe-button-container"}]}]});g.M(this,this.o);this.o.va(this.element);this.A=new g.g_(g.V("YTP_SUBSCRIBE"),null,g.V("YTP_UNSUBSCRIBE"),null,!0,!1,b.dm,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.A);this.A.va(this.o.ua["html5-subscribe-button-container"]);this.hide()},
t5=function(a){var b=g.Y(a),c=g.SJ||g.bf?{style:"will-change: opacity"}:void 0,d=b.l&&!b.B,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",aa:e,U:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{G:"div",L:"ytp-videowall-still-image",U:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",J:[{G:"span",L:"ytp-videowall-still-info-bg",J:[{G:"span",L:"ytp-videowall-still-info-content",U:c,J:[{G:"span",L:"ytp-videowall-still-info-title",J:["{{title}}"]},{G:"span",L:"ytp-videowall-still-info-author",
J:["{{author_and_views}}"]},{G:"span",L:"ytp-videowall-still-info-live",J:[g.V("YTP_LIVE")]},{G:"span",L:"ytp-videowall-still-info-duration",J:["{{duration}}"]}]}]}]},{G:"span",aa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},g.V("YTP_PLAYLIST"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (",{G:"span",J:["{{playlist_length}}"]},")"]}]},{G:"span",aa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
J:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},g.V("YTP_MIX"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (50+)"]}]}]});this.A=d;this.l=a;this.o=null;this.T("click",this.B);this.T("keypress",this.C);g.Y(a).P&&(a=a.app.da,b=this.element,g.D(a.g,b),g.Ra(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.Xe(this,(0,g.z)(a.D,a,b)))},u5=function(a){n5.call(this,a,"videowall-endscreen");
this.K=a;this.F=0;this.A=[];this.H=this.D=this.C=null;this.I=this.P=!1;this.B=new g.HF(this);g.M(this,this.B);this.M=new g.Zt(g.Fa(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.M);var b=new g.W({G:"button",aa:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":g.V("YTP_PREVIOUS")},J:[g.Boa()]});g.M(this,b);b.va(this.element);b.T("click",this.WM,this);this.N=new g.SH({G:"div",L:"ytp-endscreen-content"});g.M(this,this.N);this.N.va(this.element);b=new g.W({G:"button",aa:["ytp-button","ytp-endscreen-next"],
U:{"aria-label":g.V("YTP_NEXT")},J:[g.Coa()]});g.M(this,b);b.va(this.element);b.T("click",this.VM,this);this.o=new o5(a);g.M(this,this.o);g.jV(this.l,this.o.element,4);g.Y(a).experiments.g("new_autonav_styling")&&g.S(this.o.element,"ytp-new-autonav");this.hide()},v5=function(a){return g.kV(a.l)&&a.gq()&&!a.H},qAa=function(a){return(0,g.I)(a.suggestions,function(a){return g.WY(a)})},w5=function(a){var b=a.gt();
b!=a.P&&(a.P=b,a.l.R("autonavvisibility"))},x5=function(a){g.pV.call(this,a);
g.UG({YTP_AUTOPLAY_CANCEL:"Cancel autoplay",YTP_AUTOPLAY_NEXT:"Play next video",YTP_AUTOPLAY_PAUSED_3:"Autoplay is paused",YTP_CANCEL:"Cancel",YTP_MIX:"Mix",YTP_PLAYLIST_UP_NEXT:"Up Next",YTP_UNSUBSCRIBE:"Unsubscribe"});this.l=null;this.o=new g.HF(this);g.M(this,this.o);this.A=g.Y(a);rAa(a)?this.l=new u5(this.g):this.A.ca?this.l=new pAa(this.g):this.l=new n5(this.g);g.M(this,this.l);g.jV(this.g,this.l.element,4);this.wC();this.o.O(a,"videodatachange",this.wC,this);this.o.O(a,"crn_endscreen",this.eL,
this);this.o.O(a,"crx_endscreen",this.fL,this)},rAa=function(a){a=g.Y(a);
return a.Zc&&!a.ca};
g.p(n5,g.YH);n5.prototype.create=function(){this.created=!0};
n5.prototype.destroy=function(){this.created=!1};
n5.prototype.gq=function(){return!1};
n5.prototype.gt=function(){return!1};g.p(o5,g.W);g.h=o5.prototype;g.h.bn=function(){this.C&&(this.F.stop(),this.Ba(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.eB=function(){g.XH(this,g.MU(this.l))};
g.h.VQ=function(){window.focus();this.bn()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.bq=function(a){a=a||g.Y(this.l).experiments.l("autoplay_time")||1E4;var b=Math.min(g.iG()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.l.Va()?s5(this,!0):this.o&&this.o.start()};
g.h.fR=function(a){!g.Nd(this.A.element,g.wF(a))&&g.iX(a,this.l)&&s5(this)};
g.h.WO=function(){g.OU(this.l,!0)};
g.h.tQ=function(a){this.l.Va();this.show();p5(this,a)};
g.h.MD=function(a){this.l.Va();this.B&&this.B.oc().videoId==a.oc().videoId||oAa(this,a)};
g.h.uQ=function(){this.l.Va();q5(this);this.hide()};
g.h.V=function(){q5(this);this.bn();g.W.prototype.V.call(this)};g.p(pAa,n5);g.p(t5,g.W);t5.prototype.fk=function(){g.nV(this.l,this.element);var a=this.o.oc().videoId,b=this.o.getPlaylistId();g.g0(this.l.app,a,this.o.ee,b,void 0,void 0,void 0)};
t5.prototype.B=function(a){g.iX(a,this.l,this.A,this.o.ee||void 0)&&this.fk()};
t5.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.BF(a)||(this.fk(),g.AF(a))}};g.p(u5,n5);g.h=u5.prototype;g.h.create=function(){n5.prototype.create.call(this);var a=this.l.ea();a&&(this.C=qAa(a),this.D=a);this.Eg();this.B.O(this.l,"appresize",this.Eg);this.B.O(this.l,"onVideoAreaChange",this.Eg);this.B.O(this.l,"videodatachange",this.XM);this.B.O(this.l,"autonavchange",this.eA);this.B.O(this.l,"autonavcancel",this.UM);this.B.O(this.element,"transitionend",this.vS)};
g.h.destroy=function(){g.JF(this.B);g.Ze(this.A);this.A=[];this.C=null;n5.prototype.destroy.call(this);g.tq(this.element,"ytp-show-tiles");this.M.stop()};
g.h.gq=function(){return 1!=this.D.autonavState};
g.h.show=function(){n5.prototype.show.call(this);g.tq(this.element,"ytp-show-tiles");g.Y(this.l).g?g.au(this.M):this.M.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.OU(this.l,!1);var a=v5(this);g.kV(this.l)&&g.Y(this.l).experiments.g("ui_logging")&&g.ZU(this.l,"end",{cancelButtonShow:a?"1":"0",state:this.gq()?"enabled":"disabled"});a?(w5(this),2==this.D.autonavState?g.Y(this.l).experiments.g("fast_autonav_in_background")&&3==this.l.Di()?s5(this.o,!0):p5(this.o):3==this.D.autonavState&&
r5(this.o)):(g.OU(this.l,!0),w5(this))};
g.h.hide=function(){n5.prototype.hide.call(this);r5(this.o);w5(this)};
g.h.vS=function(a){g.wF(a)==this.element&&this.Eg()};
g.h.Eg=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");if(g.Y(this.K).experiments.g("web_player_endscreen_size_killswitch"))var a=g.Lh(this.element);else{a=g.bV(this.K);var b=g.lI(this.K);b&&(b=b.sd()?48:32,a.width-=2*b)}var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,C=e<=k-2&&n>=q*m;if((q+
1)/r*d/c>c/(q/(r+1)*d)&&C)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(C)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Zc(a.width/m||1,1,1.21);n*=g.Zc(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Kh(a,m,n);g.ph(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});oAa(this.o,this.C[0]);g.U(this.element,"ytp-endscreen-takeover",v5(this));w5(this);m+=4;
n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.$c(q+this.F,l),0!=r){u=this.A[c];u||(u=new t5(this.l),this.A[c]=u,a.appendChild(u.element));C=Math.floor(n*k/e);var H=Math.floor(m*f/b),T=Math.floor(n*(k+r)/e)-C-4,na=Math.floor(m*(f+r)/b)-H-4;g.zh(u.element,H,C);g.Kh(u.element,na,T);g.ph(u.element,"transitionDelay",(k+f)/20+"s");g.U(u.element,"ytp-videowall-still-mini",1==r);g.U(u.element,"ytp-videowall-still-large",2<r);r=
u;q=this.C[q];r.o=q;nAa(r,q,g.Y(r.l),g.rq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");u=q.ee;q=r.l;g.Y(q).P&&(q=q.app.da,r=r.element,u=u&&u.itct,C=r.getAttribute("data-visual-id"),g.D(q.g,r),g.lV(q,"onLogServerVeCreated",{id:C,tracking_params:u}));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Fd(e.element),g.Ye(e);this.A.length=c}};
g.h.XM=function(){var a=this.l.ea();this.D!=a&&(this.F=0,this.C=qAa(a),this.D=a,this.Eg())};
g.h.VM=function(){this.F+=this.A.length;this.Eg()};
g.h.WM=function(){this.F-=this.A.length;this.Eg()};
g.h.lK=function(){return!!this.o.o};
g.h.eA=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,q5(this.o),this.g&&this.Eg()):(this.I=!0,this.g&&v5(this)&&(2==a?p5(this.o):3==a&&r5(this.o)))};
g.h.UM=function(a){if(a){for(a=0;a<this.A.length;a++)g.oV(this.K,this.A[a].element,!0);this.eA(1)}else this.H=null,this.I=!1;this.Eg()};
g.h.gt=function(){return this.g&&v5(this)};g.p(x5,g.pV);g.h=x5.prototype;g.h.Fz=function(){var a=this.g.ea(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!rAa(this.g)||b;a=g.rO(a,"ypc_module");var c=g.h0(this.g.app);return b&&!a&&!c};
g.h.Ez=function(){return this.l.gt()};
g.h.hK=function(){return this.Ez()?this.l.lK():!1};
g.h.V=function(){g.hV(this.g,"endscreen");g.pV.prototype.V.call(this)};
g.h.load=function(){g.pV.prototype.load.call(this);this.l.show();g.Y(this.g).ca&&.01>Math.random()&&g.ZU(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.pV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.eL=function(a){this.Fz()&&(this.l.created||this.l.create(),"load"==a.ia&&this.load())};
g.h.fL=function(a){"load"==a.ia&&this.loaded&&this.unload()};
g.h.wC=function(){g.hV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ea().lengthSeconds-10),0);a=new g.rQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.rQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.eV(this.g,[a,b])};g.bY.endscreen=x5;})(_yt_player);
